### PR TITLE
use identity hash for memo

### PR DESCRIPTION
**Pull request by mengxr**
@irmen `memo` uses `Map<Object, Integer>` and hence memo lookup calls `Object.hashCode`. The implementation of `hashCode` may be quite expensive, e.g., `String.hashCode` scans all characters. It may be good to change the logic here. In this PR, I use `System.identityHashCode` in the map and store the object in the value. So we only re-use serialized bytes if the same object (instead of objects with the same content) appears multiple times. Please let me know whether you think this is a good change. I will fix the code style (I used spaces instead of tabs).

### CODE REVIEW

**Comment by irmen** [comment]
Looks good, but yeah, please adapt the code style.

Have you done any performance measurements to see what we gain with this change?

**Comment by mengxr** [comment]
I profiled it in PySpark. Please see the screenshot in https://issues.apache.org/jira/browse/SPARK-6288 (https://issues.apache.org/jira/secure/attachment/12704465/Screen%20Shot%202015-03-13%20at%2010.45.35%20AM.png)

**Comment by mengxr** [comment]
Okay, all tabs now:)

**Comment by irmen** [comment]
16% is quite significant indeed. How does the version with identityHashcode perform?

**Comment by mengxr** [comment]
It seems that `System.identityHashCode` has a bug: http://bugs.java.com/view_bug.do?bug_id=6378256. But this is still faster than `object.hashCode`:

screen shot 2015-03-13 at 12 30 38 pm

**Comment by irmen** [comment]
this has been released in 4.4

**Pull request merged**
