### PR TITLE
Remove StopException for control flow

### PR DESCRIPTION
**Pull request by justinuang**
- Using exceptions for control flow is very expensive for performance.
  After removing it, it basically doubled in speed.

With my benchmark here, the time went from 4762ms to 2761ms.

    package net.razorvine.pickle.test;

    import java.io.IOException;
    import java.util.ArrayList;
    import java.util.List;

    import net.razorvine.pickle.PickleException;
    import net.razorvine.pickle.Pickler;
    import net.razorvine.pickle.Unpickler;

    import org.junit.Test;

    public class PerfTest {

        @Test
        public void testPerf() throws PickleException, IOException {
            Pickler pickler = new Pickler();

            List<String> myList = new ArrayList<String>();
            for (int i = 0; i < 100; i++) {
                myList.add(String.valueOf(i));
            }

            byte[] bytes = pickler.dumps(myList);

            Unpickler unpickler = new Unpickler();

            long start = System.currentTimeMillis();
            for (int i = 0; i < 100000; i++) {
                unpickler.loads(bytes);
            }

            System.out.println(System.currentTimeMillis() - start);
        }
    }

### CODE REVIEW

**Comment by irmen** [comment]
Are you saying that even though the exception is thrown only once (at the end), removing it doubles the speed?

**Comment by justinuang** [comment]
I'm using Oracle JDK 1.8 on mac. You're right, you should only get about 3800 -> 3400ms. My measurements was because I was using debug mode. Using non-debug mode, I get about 3100 -> 2700ms.

The main thing is that if I am calling Unpickle many times with small objects, then the speed up is pretty large (I'm remembering to do non-debug mode this time).

I changed the size of the list I'm deserializing to a list of one integer, and now the times are 418 -> 213ms.

**Comment by justinuang** [comment]
Sorry for editing the commit so much =P couldn't figure out how to deal with tabs.

**Comment by irmen** [comment]
thanks.

**Pull request merged**
